// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMxQwfRqEOVuEzOvWMQFJALPGwElBrbaU',
    appId: '1:590015514136:web:9f74cd0edabeee9872656d',
    messagingSenderId: '590015514136',
    projectId: 'notes-f0757',
    authDomain: 'notes-f0757.firebaseapp.com',
    storageBucket: 'notes-f0757.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtzM_rmvagOS67W4clevkxxmq82fWb_O8',
    appId: '1:590015514136:android:7f79ef7b080388f372656d',
    messagingSenderId: '590015514136',
    projectId: 'notes-f0757',
    storageBucket: 'notes-f0757.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMxQwfRqEOVuEzOvWMQFJALPGwElBrbaU',
    appId: '1:590015514136:web:b47a2fcf6e1329c472656d',
    messagingSenderId: '590015514136',
    projectId: 'notes-f0757',
    authDomain: 'notes-f0757.firebaseapp.com',
    storageBucket: 'notes-f0757.firebasestorage.app',
  );
}
