// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT9AVCRa2VWSXrVVwLUYGFcCIgoK6jICc',
    appId: '1:880650508716:web:dcbd9353226659b0b00209',
    messagingSenderId: '880650508716',
    projectId: 'gold-mdp',
    authDomain: 'gold-mdp.firebaseapp.com',
    databaseURL: 'https://gold-mdp-default-rtdb.firebaseio.com',
    storageBucket: 'gold-mdp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8K0gJGEkQctIcQTbGSqyGhUnBQu-2Lr4',
    appId: '1:880650508716:android:24f2aba7319fbfbeb00209',
    messagingSenderId: '880650508716',
    projectId: 'gold-mdp',
    databaseURL: 'https://gold-mdp-default-rtdb.firebaseio.com',
    storageBucket: 'gold-mdp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT9AVCRa2VWSXrVVwLUYGFcCIgoK6jICc',
    appId: '1:880650508716:web:1d4052b7a19bd9afb00209',
    messagingSenderId: '880650508716',
    projectId: 'gold-mdp',
    authDomain: 'gold-mdp.firebaseapp.com',
    databaseURL: 'https://gold-mdp-default-rtdb.firebaseio.com',
    storageBucket: 'gold-mdp.firebasestorage.app',
  );
}
